#!/usr/bin/expect

spawn ssh root@192.168.1.60 'service apache2 start'

expect "password:"

send "toor\n"

spawn rsync -r  ./app ./app.cgi ./app.py ./config.py ./db_ops ./db_repository ./installLMS.sh ./kill.sh ./LMS ./lmsapp.db ./LMSDef ./makefile ./packages.config ./peopledev.com.conf ./populatedatabase.py ./README-Start-Here.txt ./README.txt ./requirements.txt ./udb.sh root@192.168.1.60:/var/www/html

expect "password:"

send "toor\n"

interact
